version: 2
updates:
  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - "terraform"
      - "maintenance"
      - "dependencies"
    reviewers:
      - "krossnine"
      - "scombat"
  - package-ecosystem: 'npm'
    directory: '/lambda/src'
    schedule:
      interval: 'weekly'
    labels:
      - "lambda"
      - "maintenance"
      - "dependencies"
    reviewers:
      - "krossnine"
      - "scombat"
