exclude: |
  (?x)^(
    examples/complete/main.tf|
    examples/disable-dashboard/main.tf|
    examples/minimal/main.tf|
    examples/with-dynamic-lambda-ttl/main.tf|
    examples/with-dynamic-log-groups/main.tf|
    examples/with-dynamic-request-ttl/main.tf|
    examples/with-dynamic-retry/main.tf|
    test/terraform/main.tf|
    test/terraform/providers.tf
  )$
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_tfsec
      args:
        - --args=--config-file=__GIT_WORKING_DIR__/.tfsec.json
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml
    - id: terraform_checkov
      args:
        - --args=--config-file __GIT_WORKING_DIR__/.checkov.yml
