AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  log-forwarder lambda function

  Sample SAM Template for Krossnine/terraform-aws-elastic-forwarder module

Globals:
  Function:
    Timeout: 9
    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  LogForwarderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          LOG_LEVEL: debug
          ELASTIC_ALLOWED_LOG_FIELDS: ''
          ELASTIC_SEARCH_INDEX: "test-index"
          ELASTIC_SEARCH_PASSWORD: "password"
          ELASTIC_SEARCH_RETRY_COUNT: "10"
          ELASTIC_SEARCH_URL: "http://localhost/eslastic"
          ELASTIC_SEARCH_USERNAME: "username"
          LOGSTASH_TIMEOUT: "3000"

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
