name: Bump & Build

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  bump-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Install ZIP & Sponge cmds
      run: sudo apt-get install -y zip moreutils

    - name: Install AWS SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main

    - name: setup git
      run: |
        sudo chmod -R ugo+rwX .
        git pull --tags
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git remote set-url origin https://x-access-token:${{ secrets.CI_GITHUB_TOKEN }}@github.com/${{ github.repository }}

    - name: Build lambda
      run: sam build
      working-directory: ./lambda

    - name: Compress lambda
      run: npm run postbuild
      working-directory: ./lambda/src

    - name: Render terraform docs & push changes
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        git-push: "false"
        config-file: .terraform-docs.yml

    - name: Add artifacts
      run: |
        sudo chmod -R ugo+rwX .
        git add -A

    - name: Bump module version
      id: semantic
      run: npx standard-version -a

    - name: Add artifacts
      run: |
        sudo chmod -R ugo+rwX .
        git add -A

    - name: Add & Push changes & tag
      run: |
        git push
        git push origin --tags
