name: Terraform release module

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions: read-all

jobs:
  call-terraform-test-workflow:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
    name: Test Terraform
    uses: ./.github/workflows/test-tf.yml

  call-lambda-test-and-build-workflow:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
    name: Test Lambda
    uses: ./.github/workflows/test-lambda.yml

  release:
    needs: [call-terraform-test-workflow, call-lambda-test-and-build-workflow]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Test lambda before release
        uses: ./.github/workflows/test-lambda.yml

      - name: Test Terraform before release
        uses: ./.github/workflows/test-tf.yml

      - name: publish release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          name: 'v${{ github.ref_name }}'
          token: ${{ github.token }}
