name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  call-terraform-test-workflow:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
    name: Test Terraform
    uses: ./.github/workflows/test-tf.yml

  call-lambda-test-workflow:
    name: Test Lambda
    uses: ./.github/workflows/test-lambda.yml

  call-lambda-build-workflow:
    needs: call-lambda-test-workflow
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
    name: Build Lambda
    uses: ./.github/workflows/build-lambda.yml

  update-module-docs:
    needs:
      - call-terraform-test-workflow
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: .
        git-push: "true"
        config-file: .terraform-docs.yml
        git-commit-message: "doc(module): update module documentation [skip ci]"
