name: Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  call-terraform-test-workflow:
    permissions:
      actions: read
      checks: read
      contents: read
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
      attestations: write
    name: Test Terraform
    uses: ./.github/workflows/test-tf.yml

  call-lambda-test-and-build-workflow:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
      attestations: write
    name: Test Lambda
    uses: ./.github/workflows/test-lambda.yml

  call-integration-tests-workflow:
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      issues: read
      id-token: write
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
      attestations: write
    uses: ./.github/workflows/integration-test.yml
